### PR TITLE
Email.php

### PR DESCRIPTION
**Pull request by heckitout**
/libraries/

### CODE REVIEW

**Comment by astroanu** [comment]
Hi, i have no idea what this file is supposed to do, since this repo is 6 years old. I don't even remember such a repo existed till now. However i'm thinking this email class is being used in the CI framework to send emails and i don't think it should be included in the repo. The method the admin wants to send emails should be based on the configuration of the application.

**Comment by heckitout** [comment]
Yeaah maybe you're right, I was playing with this repo as I am learning CI
Codeigniter and stuck at sending mail to activate and reset as SMTP is not
working..
There is clear mention about that file in first line of Installation
method,
All my time seemed waste so finely I decided to ask you about it

**Comment by astroanu** [comment]
Yea, if you configure your email settings it should work properly. But i'm not sure if this project is compatible with the latest codeigniter anymore. This is six years ago. :) Probably there are better ways to implement this.

**Comment by heckitout** [comment]
Yes My file worked well thanks,
I was just testing it ,
Anyway...
Thanks Sir,

**Pull request closed without merging**
